"""create_kanji_table

Revision ID: 001
Revises: 
Create Date: 2026-01-23 18:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '001'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'kanji',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('character', sa.String(length=1), nullable=False),
        sa.Column('meanings', sa.JSON(), nullable=False),
        sa.Column('readings_on', sa.JSON(), nullable=False),
        sa.Column('readings_kun', sa.JSON(), nullable=False),
        sa.Column('grade', sa.Integer(), nullable=True),
        sa.Column('jlpt_level', sa.Integer(), nullable=True),
        sa.Column('stroke_count', sa.Integer(), nullable=False),
        sa.Column('active', sa.Boolean(), nullable=False, server_default='0'),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(op.f('ix_kanji_character'), 'kanji', ['character'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_kanji_character', table_name='kanji')
    op.drop_table('kanji')
    # ### end Alembic commands ###
